### ISSUE TITLE
ssl server error 60

### ISSUE THREAD

**Issue by penfolduk** [snake24564/stalker#4]
dont suppose you know how to fix ssl cert problem its saying expired for server communication

**Comment by snake24564** [comment]
could you provide a screenshot of the error / problem?

**Comment by penfolduk** [comment]
its ok now sorted itself thanks

somewhere between me and server forgot to update certificates

apprentice you taking time to respond

**Comment by penfolduk** [comment]
Btw your 5.6 install script works perfectly

**Comment by snake24564** [comment]
Thanks!
